//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class New : tblinventory
    {
        public Nullable<System.DateTime> DateProduced { get; set; }
        public string CountryProduced { get; set; }
    }
}
