//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomerorder
    {
        public int OrderID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public decimal OrderCost { get; set; }
        public System.DateTime OrderTimestamp { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
    
        public virtual tblinventory tblinventory { get; set; }
    }
}
