//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAdminProgram.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsBrand", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.SerializableAttribute()]
    public partial class clsBrand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoundedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsAdminProgram.ServiceReference1.clsInventory[] InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SloganField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Founded {
            get {
                return this.FoundedField;
            }
            set {
                if ((object.ReferenceEquals(this.FoundedField, value) != true)) {
                    this.FoundedField = value;
                    this.RaisePropertyChanged("Founded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsAdminProgram.ServiceReference1.clsInventory[] Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Slogan {
            get {
                return this.SloganField;
            }
            set {
                if ((object.ReferenceEquals(this.SloganField, value) != true)) {
                    this.SloganField = value;
                    this.RaisePropertyChanged("Slogan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsInventory", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsAdminProgram.ServiceReference1.clsNew))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsAdminProgram.ServiceReference1.clsUsed))]
    public partial class clsInventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsAdminProgram.ServiceReference1.clsCustomerOrder[] CustomerOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsAdminProgram.ServiceReference1.clsCustomerOrder[] CustomerOrders {
            get {
                return this.CustomerOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrdersField, value) != true)) {
                    this.CustomerOrdersField = value;
                    this.RaisePropertyChanged("CustomerOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsNew", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.SerializableAttribute()]
    public partial class clsNew : WindowsAdminProgram.ServiceReference1.clsInventory {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryProducedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateProducedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryProduced {
            get {
                return this.CountryProducedField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryProducedField, value) != true)) {
                    this.CountryProducedField = value;
                    this.RaisePropertyChanged("CountryProduced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateProduced {
            get {
                return this.DateProducedField;
            }
            set {
                if ((this.DateProducedField.Equals(value) != true)) {
                    this.DateProducedField = value;
                    this.RaisePropertyChanged("DateProduced");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsUsed", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.SerializableAttribute()]
    public partial class clsUsed : WindowsAdminProgram.ServiceReference1.clsInventory {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemConditionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCondition {
            get {
                return this.ItemConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemConditionField, value) != true)) {
                    this.ItemConditionField = value;
                    this.RaisePropertyChanged("ItemCondition");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCustomerOrder", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.SerializableAttribute()]
    public partial class clsCustomerOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsAdminProgram.ServiceReference1.clsInventory InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPhone {
            get {
                return this.CustomerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneField, value) != true)) {
                    this.CustomerPhoneField = value;
                    this.RaisePropertyChanged("CustomerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsAdminProgram.ServiceReference1.clsInventory Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderCost {
            get {
                return this.OrderCostField;
            }
            set {
                if ((this.OrderCostField.Equals(value) != true)) {
                    this.OrderCostField = value;
                    this.RaisePropertyChanged("OrderCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderTimestamp {
            get {
                return this.OrderTimestampField;
            }
            set {
                if ((this.OrderTimestampField.Equals(value) != true)) {
                    this.OrderTimestampField = value;
                    this.RaisePropertyChanged("OrderTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrandNames", ReplyAction="http://tempuri.org/IService1/GetBrandNamesResponse")]
        string[] GetBrandNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrandNames", ReplyAction="http://tempuri.org/IService1/GetBrandNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetBrandNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrand", ReplyAction="http://tempuri.org/IService1/GetBrandResponse")]
        WindowsAdminProgram.ServiceReference1.clsBrand GetBrand(string prBrand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBrand", ReplyAction="http://tempuri.org/IService1/GetBrandResponse")]
        System.Threading.Tasks.Task<WindowsAdminProgram.ServiceReference1.clsBrand> GetBrandAsync(string prBrand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        int[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        System.Threading.Tasks.Task<int[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        WindowsAdminProgram.ServiceReference1.clsCustomerOrder GetOrder(int prItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        System.Threading.Tasks.Task<WindowsAdminProgram.ServiceReference1.clsCustomerOrder> GetOrderAsync(int prItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddItem", ReplyAction="http://tempuri.org/IService1/AddItemResponse")]
        int AddItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddItem", ReplyAction="http://tempuri.org/IService1/AddItemResponse")]
        System.Threading.Tasks.Task<int> AddItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItem", ReplyAction="http://tempuri.org/IService1/UpdateItemResponse")]
        int UpdateItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateItem", ReplyAction="http://tempuri.org/IService1/UpdateItemResponse")]
        System.Threading.Tasks.Task<int> UpdateItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItem", ReplyAction="http://tempuri.org/IService1/DeleteItemResponse")]
        int DeleteItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteItem", ReplyAction="http://tempuri.org/IService1/DeleteItemResponse")]
        System.Threading.Tasks.Task<int> DeleteItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        int AddOrder(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task<int> AddOrderAsync(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        int DeleteOrder(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task<int> DeleteOrderAsync(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsAdminProgram.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsAdminProgram.ServiceReference1.IService1>, WindowsAdminProgram.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetBrandNames() {
            return base.Channel.GetBrandNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetBrandNamesAsync() {
            return base.Channel.GetBrandNamesAsync();
        }
        
        public WindowsAdminProgram.ServiceReference1.clsBrand GetBrand(string prBrand) {
            return base.Channel.GetBrand(prBrand);
        }
        
        public System.Threading.Tasks.Task<WindowsAdminProgram.ServiceReference1.clsBrand> GetBrandAsync(string prBrand) {
            return base.Channel.GetBrandAsync(prBrand);
        }
        
        public int[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public WindowsAdminProgram.ServiceReference1.clsCustomerOrder GetOrder(int prItemID) {
            return base.Channel.GetOrder(prItemID);
        }
        
        public System.Threading.Tasks.Task<WindowsAdminProgram.ServiceReference1.clsCustomerOrder> GetOrderAsync(int prItemID) {
            return base.Channel.GetOrderAsync(prItemID);
        }
        
        public int AddItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.AddItem(prItem);
        }
        
        public System.Threading.Tasks.Task<int> AddItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.AddItemAsync(prItem);
        }
        
        public int UpdateItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.UpdateItem(prItem);
        }
        
        public System.Threading.Tasks.Task<int> UpdateItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.UpdateItemAsync(prItem);
        }
        
        public int DeleteItem(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.DeleteItem(prItem);
        }
        
        public System.Threading.Tasks.Task<int> DeleteItemAsync(WindowsAdminProgram.ServiceReference1.clsInventory prItem) {
            return base.Channel.DeleteItemAsync(prItem);
        }
        
        public int AddOrder(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            return base.Channel.AddOrder(prCustomerOrder);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            return base.Channel.AddOrderAsync(prCustomerOrder);
        }
        
        public int DeleteOrder(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            return base.Channel.DeleteOrder(prCustomerOrder);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOrderAsync(WindowsAdminProgram.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            return base.Channel.DeleteOrderAsync(prCustomerOrder);
        }
    }
}
