//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CustomerPhoneApp.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsBrand", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    public partial class clsBrand : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BrandField;
        
        private string FoundedField;
        
        private System.Collections.ObjectModel.ObservableCollection<CustomerPhoneApp.ServiceReference1.clsInventory> InventoryField;
        
        private string SloganField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Founded {
            get {
                return this.FoundedField;
            }
            set {
                if ((object.ReferenceEquals(this.FoundedField, value) != true)) {
                    this.FoundedField = value;
                    this.RaisePropertyChanged("Founded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CustomerPhoneApp.ServiceReference1.clsInventory> Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Slogan {
            get {
                return this.SloganField;
            }
            set {
                if ((object.ReferenceEquals(this.SloganField, value) != true)) {
                    this.SloganField = value;
                    this.RaisePropertyChanged("Slogan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsInventory", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerPhoneApp.ServiceReference1.clsNew))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CustomerPhoneApp.ServiceReference1.clsUsed))]
    public partial class clsInventory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BrandField;
        
        private System.Collections.ObjectModel.ObservableCollection<CustomerPhoneApp.ServiceReference1.clsCustomerOrder> CustomerOrdersField;
        
        private int ItemIDField;
        
        private System.DateTime LastModifiedField;
        
        private string ModelNameField;
        
        private decimal PriceField;
        
        private int StockQuantityField;
        
        private string StyleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CustomerPhoneApp.ServiceReference1.clsCustomerOrder> CustomerOrders {
            get {
                return this.CustomerOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrdersField, value) != true)) {
                    this.CustomerOrdersField = value;
                    this.RaisePropertyChanged("CustomerOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsNew", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    public partial class clsNew : CustomerPhoneApp.ServiceReference1.clsInventory {
        
        private string CountryProducedField;
        
        private System.Nullable<System.DateTime> DateProducedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryProduced {
            get {
                return this.CountryProducedField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryProducedField, value) != true)) {
                    this.CountryProducedField = value;
                    this.RaisePropertyChanged("CountryProduced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateProduced {
            get {
                return this.DateProducedField;
            }
            set {
                if ((this.DateProducedField.Equals(value) != true)) {
                    this.DateProducedField = value;
                    this.RaisePropertyChanged("DateProduced");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsUsed", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    public partial class clsUsed : CustomerPhoneApp.ServiceReference1.clsInventory {
        
        private System.Nullable<int> AgeField;
        
        private string ItemConditionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCondition {
            get {
                return this.ItemConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemConditionField, value) != true)) {
                    this.ItemConditionField = value;
                    this.RaisePropertyChanged("ItemCondition");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCustomerOrder", Namespace="http://schemas.datacontract.org/2004/07/SelfHost.DTO")]
    public partial class clsCustomerOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CustomerNameField;
        
        private string CustomerPhoneField;
        
        private CustomerPhoneApp.ServiceReference1.clsInventory InventoryField;
        
        private int ItemIDField;
        
        private decimal OrderCostField;
        
        private int OrderIDField;
        
        private System.DateTime OrderTimestampField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPhone {
            get {
                return this.CustomerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneField, value) != true)) {
                    this.CustomerPhoneField = value;
                    this.RaisePropertyChanged("CustomerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CustomerPhoneApp.ServiceReference1.clsInventory Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderCost {
            get {
                return this.OrderCostField;
            }
            set {
                if ((this.OrderCostField.Equals(value) != true)) {
                    this.OrderCostField = value;
                    this.RaisePropertyChanged("OrderCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderTimestamp {
            get {
                return this.OrderTimestampField;
            }
            set {
                if ((this.OrderTimestampField.Equals(value) != true)) {
                    this.OrderTimestampField = value;
                    this.RaisePropertyChanged("OrderTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetBrandNames", ReplyAction="http://tempuri.org/IService1/GetBrandNamesResponse")]
        System.IAsyncResult BeginGetBrandNames(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetBrandNames(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetBrand", ReplyAction="http://tempuri.org/IService1/GetBrandResponse")]
        System.IAsyncResult BeginGetBrand(string prBrand, System.AsyncCallback callback, object asyncState);
        
        CustomerPhoneApp.ServiceReference1.clsBrand EndGetBrand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<int> EndGetOrders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        System.IAsyncResult BeginGetOrder(int prItemID, System.AsyncCallback callback, object asyncState);
        
        CustomerPhoneApp.ServiceReference1.clsCustomerOrder EndGetOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddItem", ReplyAction="http://tempuri.org/IService1/AddItemResponse")]
        System.IAsyncResult BeginAddItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState);
        
        int EndAddItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UpdateItem", ReplyAction="http://tempuri.org/IService1/UpdateItemResponse")]
        System.IAsyncResult BeginUpdateItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState);
        
        int EndUpdateItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteItem", ReplyAction="http://tempuri.org/IService1/DeleteItemResponse")]
        System.IAsyncResult BeginDeleteItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState);
        
        int EndDeleteItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.IAsyncResult BeginAddOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState);
        
        int EndAddOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.IAsyncResult BeginDeleteOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState);
        
        int EndDeleteOrder(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CustomerPhoneApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBrandNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBrandNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CustomerPhoneApp.ServiceReference1.clsBrand Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CustomerPhoneApp.ServiceReference1.clsBrand)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<int> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<int>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CustomerPhoneApp.ServiceReference1.clsCustomerOrder Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CustomerPhoneApp.ServiceReference1.clsCustomerOrder)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CustomerPhoneApp.ServiceReference1.IService1>, CustomerPhoneApp.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetBrandNamesDelegate;
        
        private EndOperationDelegate onEndGetBrandNamesDelegate;
        
        private System.Threading.SendOrPostCallback onGetBrandNamesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBrandDelegate;
        
        private EndOperationDelegate onEndGetBrandDelegate;
        
        private System.Threading.SendOrPostCallback onGetBrandCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrdersDelegate;
        
        private EndOperationDelegate onEndGetOrdersDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrdersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrderDelegate;
        
        private EndOperationDelegate onEndGetOrderDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddItemDelegate;
        
        private EndOperationDelegate onEndAddItemDelegate;
        
        private System.Threading.SendOrPostCallback onAddItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateItemDelegate;
        
        private EndOperationDelegate onEndUpdateItemDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteItemDelegate;
        
        private EndOperationDelegate onEndDeleteItemDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddOrderDelegate;
        
        private EndOperationDelegate onEndAddOrderDelegate;
        
        private System.Threading.SendOrPostCallback onAddOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteOrderDelegate;
        
        private EndOperationDelegate onEndDeleteOrderDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBrandNamesCompletedEventArgs> GetBrandNamesCompleted;
        
        public event System.EventHandler<GetBrandCompletedEventArgs> GetBrandCompleted;
        
        public event System.EventHandler<GetOrdersCompletedEventArgs> GetOrdersCompleted;
        
        public event System.EventHandler<GetOrderCompletedEventArgs> GetOrderCompleted;
        
        public event System.EventHandler<AddItemCompletedEventArgs> AddItemCompleted;
        
        public event System.EventHandler<UpdateItemCompletedEventArgs> UpdateItemCompleted;
        
        public event System.EventHandler<DeleteItemCompletedEventArgs> DeleteItemCompleted;
        
        public event System.EventHandler<AddOrderCompletedEventArgs> AddOrderCompleted;
        
        public event System.EventHandler<DeleteOrderCompletedEventArgs> DeleteOrderCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginGetBrandNames(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBrandNames(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> CustomerPhoneApp.ServiceReference1.IService1.EndGetBrandNames(System.IAsyncResult result) {
            return base.Channel.EndGetBrandNames(result);
        }
        
        private System.IAsyncResult OnBeginGetBrandNames(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginGetBrandNames(callback, asyncState);
        }
        
        private object[] OnEndGetBrandNames(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndGetBrandNames(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBrandNamesCompleted(object state) {
            if ((this.GetBrandNamesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBrandNamesCompleted(this, new GetBrandNamesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBrandNamesAsync() {
            this.GetBrandNamesAsync(null);
        }
        
        public void GetBrandNamesAsync(object userState) {
            if ((this.onBeginGetBrandNamesDelegate == null)) {
                this.onBeginGetBrandNamesDelegate = new BeginOperationDelegate(this.OnBeginGetBrandNames);
            }
            if ((this.onEndGetBrandNamesDelegate == null)) {
                this.onEndGetBrandNamesDelegate = new EndOperationDelegate(this.OnEndGetBrandNames);
            }
            if ((this.onGetBrandNamesCompletedDelegate == null)) {
                this.onGetBrandNamesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBrandNamesCompleted);
            }
            base.InvokeAsync(this.onBeginGetBrandNamesDelegate, null, this.onEndGetBrandNamesDelegate, this.onGetBrandNamesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginGetBrand(string prBrand, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBrand(prBrand, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerPhoneApp.ServiceReference1.clsBrand CustomerPhoneApp.ServiceReference1.IService1.EndGetBrand(System.IAsyncResult result) {
            return base.Channel.EndGetBrand(result);
        }
        
        private System.IAsyncResult OnBeginGetBrand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string prBrand = ((string)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginGetBrand(prBrand, callback, asyncState);
        }
        
        private object[] OnEndGetBrand(System.IAsyncResult result) {
            CustomerPhoneApp.ServiceReference1.clsBrand retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndGetBrand(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBrandCompleted(object state) {
            if ((this.GetBrandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBrandCompleted(this, new GetBrandCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBrandAsync(string prBrand) {
            this.GetBrandAsync(prBrand, null);
        }
        
        public void GetBrandAsync(string prBrand, object userState) {
            if ((this.onBeginGetBrandDelegate == null)) {
                this.onBeginGetBrandDelegate = new BeginOperationDelegate(this.OnBeginGetBrand);
            }
            if ((this.onEndGetBrandDelegate == null)) {
                this.onEndGetBrandDelegate = new EndOperationDelegate(this.OnEndGetBrand);
            }
            if ((this.onGetBrandCompletedDelegate == null)) {
                this.onGetBrandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBrandCompleted);
            }
            base.InvokeAsync(this.onBeginGetBrandDelegate, new object[] {
                        prBrand}, this.onEndGetBrandDelegate, this.onGetBrandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginGetOrders(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrders(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<int> CustomerPhoneApp.ServiceReference1.IService1.EndGetOrders(System.IAsyncResult result) {
            return base.Channel.EndGetOrders(result);
        }
        
        private System.IAsyncResult OnBeginGetOrders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginGetOrders(callback, asyncState);
        }
        
        private object[] OnEndGetOrders(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<int> retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndGetOrders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrdersCompleted(object state) {
            if ((this.GetOrdersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrdersCompleted(this, new GetOrdersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrdersAsync() {
            this.GetOrdersAsync(null);
        }
        
        public void GetOrdersAsync(object userState) {
            if ((this.onBeginGetOrdersDelegate == null)) {
                this.onBeginGetOrdersDelegate = new BeginOperationDelegate(this.OnBeginGetOrders);
            }
            if ((this.onEndGetOrdersDelegate == null)) {
                this.onEndGetOrdersDelegate = new EndOperationDelegate(this.OnEndGetOrders);
            }
            if ((this.onGetOrdersCompletedDelegate == null)) {
                this.onGetOrdersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrdersCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrdersDelegate, null, this.onEndGetOrdersDelegate, this.onGetOrdersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginGetOrder(int prItemID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrder(prItemID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerPhoneApp.ServiceReference1.clsCustomerOrder CustomerPhoneApp.ServiceReference1.IService1.EndGetOrder(System.IAsyncResult result) {
            return base.Channel.EndGetOrder(result);
        }
        
        private System.IAsyncResult OnBeginGetOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int prItemID = ((int)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginGetOrder(prItemID, callback, asyncState);
        }
        
        private object[] OnEndGetOrder(System.IAsyncResult result) {
            CustomerPhoneApp.ServiceReference1.clsCustomerOrder retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndGetOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrderCompleted(object state) {
            if ((this.GetOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrderAsync(int prItemID) {
            this.GetOrderAsync(prItemID, null);
        }
        
        public void GetOrderAsync(int prItemID, object userState) {
            if ((this.onBeginGetOrderDelegate == null)) {
                this.onBeginGetOrderDelegate = new BeginOperationDelegate(this.OnBeginGetOrder);
            }
            if ((this.onEndGetOrderDelegate == null)) {
                this.onEndGetOrderDelegate = new EndOperationDelegate(this.OnEndGetOrder);
            }
            if ((this.onGetOrderCompletedDelegate == null)) {
                this.onGetOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrderCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrderDelegate, new object[] {
                        prItemID}, this.onEndGetOrderDelegate, this.onGetOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginAddItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddItem(prItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CustomerPhoneApp.ServiceReference1.IService1.EndAddItem(System.IAsyncResult result) {
            return base.Channel.EndAddItem(result);
        }
        
        private System.IAsyncResult OnBeginAddItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CustomerPhoneApp.ServiceReference1.clsInventory prItem = ((CustomerPhoneApp.ServiceReference1.clsInventory)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginAddItem(prItem, callback, asyncState);
        }
        
        private object[] OnEndAddItem(System.IAsyncResult result) {
            int retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndAddItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddItemCompleted(object state) {
            if ((this.AddItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddItemCompleted(this, new AddItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem) {
            this.AddItemAsync(prItem, null);
        }
        
        public void AddItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem, object userState) {
            if ((this.onBeginAddItemDelegate == null)) {
                this.onBeginAddItemDelegate = new BeginOperationDelegate(this.OnBeginAddItem);
            }
            if ((this.onEndAddItemDelegate == null)) {
                this.onEndAddItemDelegate = new EndOperationDelegate(this.OnEndAddItem);
            }
            if ((this.onAddItemCompletedDelegate == null)) {
                this.onAddItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddItemCompleted);
            }
            base.InvokeAsync(this.onBeginAddItemDelegate, new object[] {
                        prItem}, this.onEndAddItemDelegate, this.onAddItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginUpdateItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateItem(prItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CustomerPhoneApp.ServiceReference1.IService1.EndUpdateItem(System.IAsyncResult result) {
            return base.Channel.EndUpdateItem(result);
        }
        
        private System.IAsyncResult OnBeginUpdateItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CustomerPhoneApp.ServiceReference1.clsInventory prItem = ((CustomerPhoneApp.ServiceReference1.clsInventory)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginUpdateItem(prItem, callback, asyncState);
        }
        
        private object[] OnEndUpdateItem(System.IAsyncResult result) {
            int retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndUpdateItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateItemCompleted(object state) {
            if ((this.UpdateItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateItemCompleted(this, new UpdateItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem) {
            this.UpdateItemAsync(prItem, null);
        }
        
        public void UpdateItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem, object userState) {
            if ((this.onBeginUpdateItemDelegate == null)) {
                this.onBeginUpdateItemDelegate = new BeginOperationDelegate(this.OnBeginUpdateItem);
            }
            if ((this.onEndUpdateItemDelegate == null)) {
                this.onEndUpdateItemDelegate = new EndOperationDelegate(this.OnEndUpdateItem);
            }
            if ((this.onUpdateItemCompletedDelegate == null)) {
                this.onUpdateItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateItemCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateItemDelegate, new object[] {
                        prItem}, this.onEndUpdateItemDelegate, this.onUpdateItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginDeleteItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteItem(prItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CustomerPhoneApp.ServiceReference1.IService1.EndDeleteItem(System.IAsyncResult result) {
            return base.Channel.EndDeleteItem(result);
        }
        
        private System.IAsyncResult OnBeginDeleteItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CustomerPhoneApp.ServiceReference1.clsInventory prItem = ((CustomerPhoneApp.ServiceReference1.clsInventory)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginDeleteItem(prItem, callback, asyncState);
        }
        
        private object[] OnEndDeleteItem(System.IAsyncResult result) {
            int retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndDeleteItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteItemCompleted(object state) {
            if ((this.DeleteItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteItemCompleted(this, new DeleteItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem) {
            this.DeleteItemAsync(prItem, null);
        }
        
        public void DeleteItemAsync(CustomerPhoneApp.ServiceReference1.clsInventory prItem, object userState) {
            if ((this.onBeginDeleteItemDelegate == null)) {
                this.onBeginDeleteItemDelegate = new BeginOperationDelegate(this.OnBeginDeleteItem);
            }
            if ((this.onEndDeleteItemDelegate == null)) {
                this.onEndDeleteItemDelegate = new EndOperationDelegate(this.OnEndDeleteItem);
            }
            if ((this.onDeleteItemCompletedDelegate == null)) {
                this.onDeleteItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteItemCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteItemDelegate, new object[] {
                        prItem}, this.onEndDeleteItemDelegate, this.onDeleteItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginAddOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddOrder(prCustomerOrder, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CustomerPhoneApp.ServiceReference1.IService1.EndAddOrder(System.IAsyncResult result) {
            return base.Channel.EndAddOrder(result);
        }
        
        private System.IAsyncResult OnBeginAddOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder = ((CustomerPhoneApp.ServiceReference1.clsCustomerOrder)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginAddOrder(prCustomerOrder, callback, asyncState);
        }
        
        private object[] OnEndAddOrder(System.IAsyncResult result) {
            int retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndAddOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddOrderCompleted(object state) {
            if ((this.AddOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddOrderCompleted(this, new AddOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddOrderAsync(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            this.AddOrderAsync(prCustomerOrder, null);
        }
        
        public void AddOrderAsync(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, object userState) {
            if ((this.onBeginAddOrderDelegate == null)) {
                this.onBeginAddOrderDelegate = new BeginOperationDelegate(this.OnBeginAddOrder);
            }
            if ((this.onEndAddOrderDelegate == null)) {
                this.onEndAddOrderDelegate = new EndOperationDelegate(this.OnEndAddOrder);
            }
            if ((this.onAddOrderCompletedDelegate == null)) {
                this.onAddOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddOrderCompleted);
            }
            base.InvokeAsync(this.onBeginAddOrderDelegate, new object[] {
                        prCustomerOrder}, this.onEndAddOrderDelegate, this.onAddOrderCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CustomerPhoneApp.ServiceReference1.IService1.BeginDeleteOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteOrder(prCustomerOrder, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CustomerPhoneApp.ServiceReference1.IService1.EndDeleteOrder(System.IAsyncResult result) {
            return base.Channel.EndDeleteOrder(result);
        }
        
        private System.IAsyncResult OnBeginDeleteOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder = ((CustomerPhoneApp.ServiceReference1.clsCustomerOrder)(inValues[0]));
            return ((CustomerPhoneApp.ServiceReference1.IService1)(this)).BeginDeleteOrder(prCustomerOrder, callback, asyncState);
        }
        
        private object[] OnEndDeleteOrder(System.IAsyncResult result) {
            int retVal = ((CustomerPhoneApp.ServiceReference1.IService1)(this)).EndDeleteOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteOrderCompleted(object state) {
            if ((this.DeleteOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteOrderCompleted(this, new DeleteOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteOrderAsync(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder) {
            this.DeleteOrderAsync(prCustomerOrder, null);
        }
        
        public void DeleteOrderAsync(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, object userState) {
            if ((this.onBeginDeleteOrderDelegate == null)) {
                this.onBeginDeleteOrderDelegate = new BeginOperationDelegate(this.OnBeginDeleteOrder);
            }
            if ((this.onEndDeleteOrderDelegate == null)) {
                this.onEndDeleteOrderDelegate = new EndOperationDelegate(this.OnEndDeleteOrder);
            }
            if ((this.onDeleteOrderCompletedDelegate == null)) {
                this.onDeleteOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteOrderCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteOrderDelegate, new object[] {
                        prCustomerOrder}, this.onEndDeleteOrderDelegate, this.onDeleteOrderCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CustomerPhoneApp.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<CustomerPhoneApp.ServiceReference1.IService1>, CustomerPhoneApp.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<CustomerPhoneApp.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBrandNames(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetBrandNames", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetBrandNames(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetBrandNames", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBrand(string prBrand, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prBrand;
                System.IAsyncResult _result = base.BeginInvoke("GetBrand", _args, callback, asyncState);
                return _result;
            }
            
            public CustomerPhoneApp.ServiceReference1.clsBrand EndGetBrand(System.IAsyncResult result) {
                object[] _args = new object[0];
                CustomerPhoneApp.ServiceReference1.clsBrand _result = ((CustomerPhoneApp.ServiceReference1.clsBrand)(base.EndInvoke("GetBrand", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetOrders", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<int> EndGetOrders(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<int> _result = ((System.Collections.ObjectModel.ObservableCollection<int>)(base.EndInvoke("GetOrders", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetOrder(int prItemID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prItemID;
                System.IAsyncResult _result = base.BeginInvoke("GetOrder", _args, callback, asyncState);
                return _result;
            }
            
            public CustomerPhoneApp.ServiceReference1.clsCustomerOrder EndGetOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                CustomerPhoneApp.ServiceReference1.clsCustomerOrder _result = ((CustomerPhoneApp.ServiceReference1.clsCustomerOrder)(base.EndInvoke("GetOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prItem;
                System.IAsyncResult _result = base.BeginInvoke("AddItem", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prItem;
                System.IAsyncResult _result = base.BeginInvoke("UpdateItem", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUpdateItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UpdateItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteItem(CustomerPhoneApp.ServiceReference1.clsInventory prItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prItem;
                System.IAsyncResult _result = base.BeginInvoke("DeleteItem", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDeleteItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DeleteItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prCustomerOrder;
                System.IAsyncResult _result = base.BeginInvoke("AddOrder", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddOrder", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteOrder(CustomerPhoneApp.ServiceReference1.clsCustomerOrder prCustomerOrder, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prCustomerOrder;
                System.IAsyncResult _result = base.BeginInvoke("DeleteOrder", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDeleteOrder(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DeleteOrder", _args, result)));
                return _result;
            }
        }
    }
}
